#!/usr/bin/env bash

dns_config() {
    local domain=$1
    local subdomain=$2

    dig_output=$(dig "$subdomain.$domain" +short)

    if [ -z "$dig_output" ]; then
        echo "Error: Unable to retrieve DNS information for $subdomain.$domain"
        return
    fi

    record_type=$(dig "$subdomain.$domain" | awk '/IN/{print $4}')
    destination=$(echo "$dig_output" | head -n1)

    printf "The subdomain %s is a %s record and points to %s\n" "$subdomain" "$record_type" "$destination"
}

if [ "$#" == 1 ]; then
    dns_config "$1" "www"
    dns_config "$1" "lb-01"
    dns_config "$1" "web-01"
    dns_config "$1" "web-02"
elif [ "$#" == 2 ]; then
    dns_config "$1" "$2"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

