#!/usr/bin/env bash
# Installs and sets up HAProxy

# Update package lists
apt-get update

# Install HAProxy
apt-get install -y haproxy

# Enable HAProxy
echo "ENABLED=1" > /etc/default/haproxy

# Configure HAProxy to listen to web1 and web2 servers
echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    balance roundrobin
    option httpclose
    option forwardfor
    server web-01 100.26.159.155:80 check
    server web-02 100.26.122.170:80 check
" > /etc/haproxy/haproxy.cfg

# Start HAProxy service
service haproxy start

# Output the required strings
echo '["web-01", "web-02"]'

