#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a round-robin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAProxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# Edit the HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
defaults
    timeout client 30s
    timeout server 30s
    timeout connect 5s

frontend silvia_frontend
    bind *:80
    mode http
    default_backend silvia_backend

backend silvia_backend
    balance roundrobin
    mode http
    server web-01 100.26.159.155:80 check
    server web-02 100.26.122.170:80 check
EOF

# Enable HAProxy to be started by an init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAProxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart
